baseurl: 'http://integral.github.io/batagov'
permalink: pretty
markdown: kramdown
kramdown:
  remove_block_html_tags: false
  html_to_native: true
prose:
  rooturl: ''
  siteurl: 'http://integral.github.io/batagov'
  media: 'assets/media'
  metadata:
    _posts/records:
      - name: "category"
        field:
          element: "hidden"
          value: "records"
      - name: "layout"
        field:
          element: "hidden"
          value: "record"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "year"
        field:
          element: "text"
          label: "Year"
          value: ""
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "short description"
      - name: "artwork"
        field:
          element: "text"
          label: "Artwork url"
          value: ""
      - name: "thumbnail"
        field:
          element: "text"
          label: "Thumbnail url"
          value: ""
      - name: "buy"
        field:
          element: "text"
          label: "Buy record url"
          value: ""
      - name: "itunes"
        field:
          element: "text"
          label: "Itunes url"
          value: ""
      - name: "type"
        field:
          element: "select"
          label: "Composer"
          options:
            - name: 'Composer'
              value: 'composer'
            - name: 'Performer'
              value: 'performer'
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          options:
            - name: 'English'
              value: 'en'
            - name: 'Russian'
              value: 'ru'
      - name: "l10n"
        field:
          element: "text"
          label: "Translation"
          value: ""
      - name: "published"
        field:
          element: "hidden"
          value: "true"
    _posts/static:
      - name: "category"
        field:
          element: "hidden"
          value: "static"
      - name: "layout"
        field:
          element: "hidden"
          value: "static"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          options:
            - name: 'English'
              value: 'en'
            - name: 'Russian'
              value: 'ru'
      - name: "l10n"
        field:
          element: "text"
          label: "Translation"
          value: ""
      - name: "published"
        field:
          element: "hidden"
          value: "true"