baseurl: 'http://integral.github.io/batagov'
permalink: pretty
markdown: kramdown
kramdown:
  remove_block_html_tags: false
  html_to_native: true
prose:
  rooturl: '_posts'
  siteurl: 'http://integral.github.io/batagov'
  media: '/assets/media'
  metadata:
    _posts/records:
      - name: "category"
        field:
          element: "hidden"
          value: "records"
      - name: "layout"
        field:
          element: "hidden"
          value: "record"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "year"
        field:
          element: "text"
          label: "Year"
          value: ""
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "short description"
      - name: "artwork"
        field:
          element: "text"
          label: "Artwork url"
          value: ""
      - name: "thumbnail"
        field:
          element: "text"
          label: "Thumbnail url"
          value: ""
      - name: "buy"
        field:
          element: "text"
          label: "Buy record url"
          value: ""
      - name: "itunes"
        field:
          element: "text"
          label: "Itunes url"
          value: ""
      - name: "type"
        field:
          element: "select"
          label: "Type"
          options:
            - name: 'Composer'
              value: 'composer'
            - name: 'Performer'
              value: 'performer'
      - name: "front"
        field:
          element: "checkbox"
          label: "Front page"
          value: "false"
      - name: "teaser"
        field:
          element: "text"
          label: "Teaser"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          options:
            - name: 'English'
              value: 'en'
            - name: 'Russian'
              value: 'ru'
      - name: "l10n"
        field:
          element: "text"
          label: "Translation"
          value: ""
      - name: "published"
        field:
          element: "hidden"
          value: "true"
    _posts/live:
      - name: "category"
        field:
          element: "hidden"
          value: "live"
      - name: "layout"
        field:
          element: "hidden"
          value: "live"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "year"
        field:
          element: "text"
          label: "Year"
          value: ""
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "short description"
      - name: "artwork"
        field:
          element: "text"
          label: "Artwork url"
          value: ""
      - name: "thumbnail"
        field:
          element: "text"
          label: "Thumbnail url"
          value: ""
      - name: "live"
        field:
          element: "checkbox"
          label: "Live"
          value: "false"
      - name: "type"
        field:
          element: "select"
          label: "Type"
          options:
            - name: 'Video'
              value: 'video'
            - name: 'Audio'
              value: 'audio'
      - name: "front"
        field:
          element: "checkbox"
          label: "Front page"
          value: "false"
      - name: "teaser"
        field:
          element: "text"
          label: "Teaser"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          options:
            - name: 'English'
              value: 'en'
            - name: 'Russian'
              value: 'ru'
      - name: "l10n"
        field:
          element: "text"
          label: "Translation"
          value: ""
      - name: "published"
        field:
          element: "hidden"
          value: "true"
    _posts/words:
      - name: "category"
        field:
          element: "hidden"
          value: "words"
      - name: "layout"
        field:
          element: "hidden"
          value: "words"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "subtitle"
        field:
          element: "text"
          label: "Subtitle"
          value: ""
          placeholder: "short description"
      - name: "source"
        field:
          element: "text"
          label: "Source"
          value: ""
          placeholder: "source of publication"
      - name: "year"
        field:
          element: "text"
          label: "Year"
          value: ""
      - name: "type"
        field:
          element: "select"
          label: "Type"
          options:
            - name: 'Text'
              value: 'text'
            - name: 'About'
              value: 'about'
            - name: 'Interview'
              value: 'interview'
            - name: 'Other'
              value: 'other'
      - name: "redirect"
        field:
          element: "text"
          label: "Redirect"
          value: ""
          placeholder: "link to external article"
      - name: "front"
        field:
          element: "checkbox"
          label: "Front page"
          value: "false"
      - name: "teaser"
        field:
          element: "text"
          label: "Teaser"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          options:
            - name: 'English'
              value: 'en'
            - name: 'Russian'
              value: 'ru'
      - name: "l10n"
        field:
          element: "text"
          label: "Translation"
          value: ""
      - name: "published"
        field:
          element: "hidden"
          value: "true"
    _posts/static:
      - name: "category"
        field:
          element: "hidden"
          value: "static"
      - name: "layout"
        field:
          element: "hidden"
          value: "static"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "menu"
        field:
          element: "text"
          label: "Menu"
          value: ""     
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          options:
            - name: 'English'
              value: 'en'
            - name: 'Russian'
              value: 'ru'
      - name: "l10n"
        field:
          element: "text"
          label: "Translation"
          value: ""
      - name: "published"
        field:
          element: "hidden"
          value: "true"