baseurl: 'http://integral.github.io/batagov'
permalink: pretty
markdown: rdiscount
prose:
  rooturl: ''
  siteurl: 'http://integral.github.io/batagov'
  media: 'assets/media'
  metadata:
    _posts/records:
      - name: "category"
        field:
          element: "hidden"
          value: "discography"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "year"
        field:
          element: "text"
          label: "Year"
          value: ""
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "short description"
      - name: "thumbnail"
        field:
          element: "text"
          label: "Thumbnail url"
          value: ""
      - name: "type"
        field:
          element: "select"
          label: "Composer"
          options:
            - name: 'Composer'
              value: 'composer'
            - name: 'Performer'
              value: 'performer'
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""